### ISSUE TITLE
Wired MBUS protocol?

### ISSUE THREAD

**Issue by jakobschou** [wmbusmeters/wmbusmeters-ha-addon#4]
Is it possible to use this addon with a wired MBUS master to usb?

**Comment by BIBOLV** [comment]
Yes, [it is](https://github.com/weetmuts/wmbusmeters#bus-aliases-and-polling) possible, but this is new version of wmbusmeters ha addon version that is not yet ready for usage, so for now please use old version from https://github.com/weetmuts/wmbusmeters. 
You can search also discussions and issues at https://github.com/weetmuts/wmbusmeters for this topic.
